#                Assignment#1

In [2]:
# importing numpy
import numpy as np

# Difficult level Easy

creating null vector of 0's size 10

In [3]:
vector_1 = np.zeros(10)
print(vector_1)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


Creating a vector with values ranging from 10 to 49

In [4]:
v = np.arange(10 , 50) 
""" Here is use the 50 instead of 49 because in numpy arry last
value is excluded and i want values exact 10 to 49 """
print(v)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


Shape of previous array

In [5]:
v.shape

(40,)

Type of previous array

In [6]:
v.dtype

dtype('int32')

numpy version and the configuration

In [7]:
print(np.__version__ , " Numpy version" , end = "\n\n")
print(np.show_config() , " Numpy configuration")

1.18.1  Numpy version

blas_mkl_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/hp/anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl', 'C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl\\include', 'C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl\\lib', 'C:/Users/hp/anaconda3\\Library\\include']
blas_opt_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/hp/anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl', 'C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl\\include', 'C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\window

Dimension of the array 

In [8]:
v.ndim

1

Boolean array with all the True values

In [9]:
bool_vector = np.ones(10 , dtype = bool)
print(bool_vector)

[ True  True  True  True  True  True  True  True  True  True]


2D array

In [10]:
two_d = np.arange(0 , 20).reshape(4 , 5)
# two_d = two_d.reshape(4 , 5)
print(two_d)
print(two_d.ndim)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]
2


3D array

In [11]:
# d3 = np.array([ [[1 , 2] , [3 , 4]],[[5 , 6] ,[7 , 8]] ])
d3 = np.arange(0 , 40).reshape(2 , 4 , 5)
print(d3.ndim)
print(d3)

3
[[[ 0  1  2  3  4]
  [ 5  6  7  8  9]
  [10 11 12 13 14]
  [15 16 17 18 19]]

 [[20 21 22 23 24]
  [25 26 27 28 29]
  [30 31 32 33 34]
  [35 36 37 38 39]]]


Reverse  vector 

In [12]:
vec = np.arange(1 , 11)

# re_vector = np.flipud(vec)

re_vector = vec[: :-1]

print(re_vector)

[10  9  8  7  6  5  4  3  2  1]


null vector of size 10 but the fifth value which is 1

In [13]:
null_v = np.zeros(10)
null_v[4] = 1
print(null_v)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


3x3 identity matrix

In [14]:
iden_mat = np.identity(3)
print(iden_mat)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


Convert the data type of the given array from int to float

In [15]:
arr = np.array([1, 2, 3, 4, 5])
print(str(arr.dtype) + "  data type of arry befor changing", end = "\n\n")
arr1 = arr.astype(np.float64)
print(str(arr1.dtype) + "  data type of arry after changing")

int32  data type of arry befor changing

float64  data type of arry after changing


Multipliction of arrays

In [16]:
arr1 = np.array([[1., 2., 3.], [4., 5., 6.]]) 
arr2 = np.array([[0., 4., 1.], [7., 2., 12.]])
arr3 = arr1 * arr2
print(arr3)

[[ 0.  8.  3.]
 [28. 10. 72.]]


array by comparing both the arrays provided above

In [17]:
new_cam_arr = np.array( arr1 == arr2)
print(new_cam_arr)

[[False False False]
 [False False False]]


Extract all odd numbers from arr with values(0-9)

In [18]:
arr= np.array([0  , 1 , 2 , 3 , 4 , 9 , 6 , 0 , 9])
ar = arr[arr % 2 == 1]
print(ar)

[1 3 9 9]


Replacing all odd numbers to -1 from previous array

In [19]:
 arr[arr % 2 == 1] = -1
print(arr)

[ 0 -1  2 -1  4 -1  6  0 -1]


Replacing the values of indexes 5,6,7 and 8 to 12

In [20]:
arr = np.arange(10)
arr[5:9] = 12
print(arr)

[ 0  1  2  3  4 12 12 12 12  9]


Creating a 2d array with 1 on the border and 0 inside

In [21]:
x = np.ones((5 , 5))
print(x , end= "\n\n\n")

x[1:-1 , 1:-1] = 0
print(x)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


# Difficulty Level Medium

Replacing the value 5 to 12

In [22]:
arr2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
arr2d[1:2 , 1:2] = 12
print(arr2d)

[[ 1  2  3]
 [ 4 12  6]
 [ 7  8  9]]


Convert all the values of 1st array to 64

In [23]:
arr3d = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])[0].astype(np.float64)
# arr3d[1].astype(np.float64)
print(arr3d)

[[1. 2. 3.]
 [4. 5. 6.]]


Making a 2-Dimensional array with values 0-9 and slice out the first 1st 1-D array from it

In [24]:
arr2d = np.arange(0 , 10).reshape(2 , 5)
# first_1d = arr2d[0:1]
first_1d = arr2d[0]
print(first_1d)

[0 1 2 3 4]



Making a 2-Dimensional array with values 0-9 and slice out the third column but only the first two rows

In [25]:
arr2d = np.linspace(0 , 9 , 20).reshape(4 , 5)
# print(arr2d)
arr_3col = arr2d[:2 , 3:4]
print(arr_3col)

[[1.42105263]
 [3.78947368]]



Creating a 10x10 array with random values and find the minimum and maximum values

In [26]:
x = np.random.random((10 , 10))
mini , maxi = x.min() , x.max()
print(mini , " Minimum value of x")
print(maxi , "  Maximum value of x")

0.027169208292988634  Minimum value of x
0.9988435406418573   Maximum value of x


Findind the common items between a and b

In [27]:
a = np.array([1,2,3,2,3,4,3,4,5,6]) 
b = np.array([7,2,10,2,7,4,9,4,9,8])
comon = np.intersect1d(a , b)
print(comon)

[2 4]


Finding the positions where elements of a and b match

In [28]:
same_index = (np.where(a==b))
print(same_index)

(array([1, 3, 5, 7], dtype=int64),)


Finding all the values from array data where the values from array names
are not equal to Will

In [37]:
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])
data = np.random.randn(7, 4)
arr = [names == "Will"]
data[arr]

[[-0.36156877 -1.26457338  2.6144444   0.77573802]
 [ 0.73328616  1.11645278  1.14564102 -0.45362977]
 [ 0.19334427  0.21020896  1.49240205 -0.42854586]
 [ 0.41869148 -1.73169604  0.0109828   0.18793096]
 [-0.35069478 -0.40103458  0.84527377  1.14203273]
 [ 1.8153376  -0.84689368 -1.35148973  0.15456197]
 [ 0.11223902  0.66980797 -0.96680255 -0.37781717]]


C:\Users\hp\anaconda3\lib\site-packages\ipykernel_launcher.py:5: FutureWarning: Using a non-tuple sequence for multidimensional indexing is deprecated; use `arr[tuple(seq)]` instead of `arr[seq]`. In the future this will be interpreted as an array index, `arr[np.array(seq)]`, which will result either in an error or a different result.
  """


array([[ 0.19334427,  0.21020896,  1.49240205, -0.42854586],
       [-0.35069478, -0.40103458,  0.84527377,  1.14203273]])

Find all the values from array data where the values from array names are not equal to Will and Joe

In [46]:
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])
data = np.random.randn(7, 4)
arr = [names != "Will" ]
arr2 = [names != "Joe"]
print(data[arr] , " Values are note equal to Will" , end = "\n\n\n")
print(data[arr2] , " Values are note equal to Joe")

[[-0.46284223  1.2890667   1.91042071 -0.84006409]
 [-1.31903751  0.45857215  2.46230352  1.57952112]
 [-0.01998842 -0.13500092  0.89439619 -0.04825716]
 [ 0.67414873  0.30035484 -1.03008072  0.68028373]
 [-0.20240147  1.48342133  0.56376364  3.00414647]]  Values are note equal to Will


[[-0.46284223  1.2890667   1.91042071 -0.84006409]
 [ 0.34422441  0.2406908  -0.51521227 -1.24797847]
 [-0.01998842 -0.13500092  0.89439619 -0.04825716]
 [ 0.11510605 -0.49016772 -0.7198123   0.20784491]]  Values are note equal to Joe


C:\Users\hp\anaconda3\lib\site-packages\ipykernel_launcher.py:5: FutureWarning: Using a non-tuple sequence for multidimensional indexing is deprecated; use `arr[tuple(seq)]` instead of `arr[seq]`. In the future this will be interpreted as an array index, `arr[np.array(seq)]`, which will result either in an error or a different result.
  """
C:\Users\hp\anaconda3\lib\site-packages\ipykernel_launcher.py:6: FutureWarning: Using a non-tuple sequence for multidimensional indexing is deprecated; use `arr[tuple(seq)]` instead of `arr[seq]`. In the future this will be interpreted as an array index, `arr[np.array(seq)]`, which will result either in an error or a different result.
  


# Difficulty Level Hard

Create a 2D array of shape 5x3 to contain decimal numbers between 1 and 15.

In [51]:
arr  = np.arange(1 , 16).reshape(5 , 3).astype(np.float64)
#  arr.astype(np.float64)
print(arr)
print(arr.ndim)
print(arr.shape)

[[ 1.  2.  3.]
 [ 4.  5.  6.]
 [ 7.  8.  9.]
 [10. 11. 12.]
 [13. 14. 15.]]
2
(5, 3)


Create an array of shape (2, 2, 4) with decimal numbers between 1 to 16.

In [52]:
arr  = np.arange(1 , 17).reshape(2 , 2 , 4)
print(arr.ndim)
print(arr)

3
[[[ 1  2  3  4]
  [ 5  6  7  8]]

 [[ 9 10 11 12]
  [13 14 15 16]]]


Create an array of size 10, and find the square root of every element in the array, if the values less than 0.5, replace them with 0

In [56]:
arr = np.sqrt(np.arange(0 , 11))
print(arr)
arr[ arr == 0.5 ] = 0
print(arr)

[0.         1.         1.41421356 1.73205081 2.         2.23606798
 2.44948974 2.64575131 2.82842712 3.         3.16227766]
[0.         1.         1.41421356 1.73205081 2.         2.23606798
 2.44948974 2.64575131 2.82842712 3.         3.16227766]


 Create two random arrays of range 12 and make an array with the maximum values between each element of the two arrays

In [62]:
arr1 = np.random.random(12)
arr2 = np.random.random(12)
arr3 = np.maximum(arr1 , arr2)
print(arr3)

[0.93108506 0.98876455 0.63687409 0.88133359 0.6398815  0.87510863
 0.85032826 0.29247446 0.95138488 0.99995845 0.38637779 0.59881416]


Find the unique names and sort them out!

In [63]:
names=np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])
np.unique(names)

array(['Bob', 'Joe', 'Will'], dtype='<U4')

From array a remove all items present in array b

In [67]:
a = np.array([1,2,3,4,5])
b = np.array([5,6,7,8,9])
# final = set(a) - set(b)
final = np.setdiff1d(a , b)
print(final)

[1 2 3 4]


Following is the input NumPy array delete column two and insert following new column in its place.

In [93]:
sampleArray= np.array([[34,43,73],[82,22,12],[53,94,66]])
newColumn = np.array([[10,10,10]])
sampleArray[2] = newColumn
print(sampleArray)


[[34 43 73]
 [82 22 12]
 [10 10 10]]



Find the dot product of the above two matrix

In [97]:
x = np.array([[1., 2., 3.], [4., 5., 6.]])
y = np.array([[6., 23.], [-1, 7], [8, 9]]).reshape(2 , 3)
dot_xy = x*y
print(dot_xy)

[[ 6. 46. -3.]
 [28. 40. 54.]]


Generate a matrix of 20 random values and find its cumulative sum

In [98]:
ran_arr = np.random.random(20)
cumutative_sum = np.cumsum(ran_arr)
print(cumutative_sum)

[ 0.23089905  0.5821444   0.61492118  1.52080443  2.2040751   3.17590598
  3.89685606  4.07525189  4.56850427  5.28808566  5.511026    6.00121001
  6.89451023  7.77549281  8.52437083  9.16543169  9.89314141 10.1047754
 10.35502003 10.82745483]
